version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ../tmp/mongodb/data:/data/db # Think about using a volume for data persistence (for now it's inside tmp)
