name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: master

      - run: npm ci
      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci

      # Run prebuild to ensure that the build dependencies are installed
      - run: npx nx affected -t prebuild

      - run: npx nx affected -t build --parallel=3
