name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get previous commit SHA
        run: echo "::set-env name=PREVIOUS_COMMIT_SHA::$(git rev-parse HEAD^)"

      - uses: nrwl/nx-set-shas@v3
        with:
          sha: ${{ env.PREVIOUS_COMMIT_SHA }}

      - run: npm ci

      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3
